# hero_data.py

FRAG_HEROES = [
    {
        "name": "Dan",
        "search_name": "dan",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Jet", "Vandal", "Cleo", "Long Shot"],
        "weapon": "Double Gun",
        "ability": "Regeneration (Instantly heals himself!)"
    },
    {
        "name": "Jet",
        "search_name": "jet",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "C",
        "teammates": ["PocaHunter", "Rippin Finn", "Gigagoo", "Hades5.1"],
        "weapon": "Plasma Launcher",
        "ability": "Jet Pack (Boost yourself in the air then hover until you reach the ground!)"
    },
    {
        "name": "Nad",
        "search_name": "nad",
        "rarity": "Legendary",
        "role": "Attacker",
        "tier": "S",
        "teammates": ["Sparky", "Didi", "Dolb", "Ripper"],
        "weapon": "Pulse Blasters",
        "ability": "Blink of an eye (Dash almost instantly in one direction!)"
    },
    {
        "name": "Sparky",
        "search_name": "sparky",
        "rarity": "Rare",
        "role": "Center",
        "tier": "A",
        "teammates": ["Lolly Pop", "Redshadow", "Jack & Timmy", "Cyber agent"],
        "weapon": "Elderwood Wand",
        "ability": "Children of the Forest (Calls upon the spirit of the forest to help him defend his team, or attack his enemies!)"
    },
    {
        "name": "Cyber Agent",
        "search_name": "cyber agent",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Big Paku", "Shino-B", "Lucha Muerta", "Bibi"],
        "weapon": "The Bugs Killer",
        "ability": "Pulsar Shield (Deploys a shield pulsing at regular intervals, slowing and weakning enemies in front of him!)"
    },
    {
        "name": "Jack & Timmy",
        "search_name": "jack & timmy",
        "rarity": "Epic",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Sparky", "Cyber Agent", "Dolb", "Nad"],
        "weapon": "The Truancy Gun",
        "ability": "Sling-Swing Surprise (Throws stones at enemies!)"
    },
    {
        "name": "Dolb",
        "search_name": "dolb",
        "rarity": "Common",
        "role": "Defender",
        "tier": "S",
        "teammates": ["Rick Rock", "Dan", "Ripper", "Virus"],
        "weapon": "Lasertune",
        "ability": "Bunker Beats (creates several magnetic shock waves on one of the bunkers!)"
    },
    {
        "name": "Evil Piper",
        "rarity": "Common",
        "search_name": "evil piper",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Inferno", "Marco Pollo", "Big Paku", "Didi"],
        "weapon": "Evilaser",
        "ability": "Hello Darkness (Releases a sudden blast of Dark Energy, Evil Piper will then float and shoot balls of Fire!)"
    },
    {
        "name": "Jab",
        "search_name": "jab",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Cyber Agent", "Krystal", "Boomi", "Queen Unicorn"],
        "weapon": "Cannon Punch",
        "ability": "Block! (Creates a holo-shield to protect Jab!)"
    },
    {
        "name": "Lolly Pop",
        "search_name": "lolly pop",
        "rarity": "Common",
        "role": "Center",
        "tier": "B",
        "teammates": ["Wyatt", "Dunkan", "BibiTM", "Queen Unicorn"],
        "weapon": "Magicandy Rod",
        "ability": "Jelly Spring (Drops a jumping jelly!)"
    },
    {
        "name": "Queen Unicorn",
        "search_name": "queen unicorn",
        "rarity": "Common",
        "role": "Defender",
        "tier": "A",
        "teammates": ["Nad", "Sparky", "Dolb", "Big Paku"],
        "weapon": "Dazzle Gun",
        "ability": "Twinkle Force (Throw a colorful remnant to slow down and damage enemies in the range!)"
    },
    {
        "name": "Piper Reese",
        "search_name": "piper reese",
        "rarity": "Rare",
        "role": "Camp",
        "tier": "A",
        "teammates": ["Lolly Pop", "Didi", "Dj Equalizer", "Blot"],
        "weapon": "Magic Mic",
        "ability": "Somersault (Shoots Deadly Glitter grenades!)"
    },
    {
        "name": "Didi",
        "search_name": "didi",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Cipher", "Cheryl", "Long Shot", "Rick Rock"],
        "weapon": "Bouncing Ball Cannon",
        "ability": "Mega-Smash (Fires a powerful projectile!)"
    },
    {
        "name": "DJ Equalizer",
        "search_name": "dj equalizer",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "A",
        "teammates": ["Nad", "Cleo", "Cyber Agent", "Big Paku"],
        "weapon": "Electro-Cannon",
        "ability": "Drop the Beat! (Shoots a Discoball that makes everyone in the area dance!)"
    },
    {
        "name": "Blot",
        "search_name": "blot",
        "rarity": "Rare",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Eagle Eye", "Izuna", "Andrometa", "Ollie"],
        "weapon": "Symbiotic Hand",
        "ability": "Slime-Coming (Turns into a puddle of slime!)"
    },
    {
        "name": "Cipher",
        "search_name": "cipher",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Rick Rock", "Dj Equalizer", "Nad", "Ripper"],
        "weapon": "Dev Gun",
        "ability": "Hack Wave (Activate a digital wave, hit enemies are slowed down, take increased damage and cannot use their ability for a few seconds!)"
    },
    {
        "name": "Cheryl",
        "search_name": "cheryl",
        "rarity": "Common",
        "role": "Center",
        "tier": "B",
        "teammates": ["Andrometa", "Queen Boom", "Fraggenstien", "Piper Reese"],
        "weapon": "Rock and Roll",
        "ability": "Showtime (Throws a Burning Fire trail!)"
    },
    {
        "name": "Long Shot",
        "search_name": "long shot",
        "rarity": "Common",
        "role": "Camp",
        "tier": "A",
        "teammates": ["Ark-On", "Cyber Agent", "Jack & Timmy", "Hunter"],
        "weapon": "Sniper rifle",
        "ability": "Zoom (Zooms at long range and see enemies through walls!)"
    },
    {
        "name": "Rick Rock",
        "search_name": "rick rock",
        "rarity": "Rare",
        "role": "Center",
        "tier": "B",
        "teammates": ["Blaise", "Sparky", "Cipher", "Big Paku"],
        "weapon": "Shocking Guitar",
        "ability": "Sound Wall (Blast a sound wave that stuns enemies in range!)"
    },
    {
        "name": "Big Paku",
        "search_name": "big paku",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Cyber Agent", "Inferno", "Dolb", "Nad"],
        "weapon": "Rocket Launcher",
        "ability": "Rocket Burst (Shoot several rockets at once!)"
    },
    {
        "name": "Poca Hunter",
        "search_name": "poca hunter",
        "rarity": "Common",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Jay B", "Miss J", "Miss Bunny", "Ron1n"],
        "weapon": "Energy Bow",
        "ability": "Triple Frag (Shoot 3 explosive arrows in a spread!)"
    },
    {
        "name": "Desperados",
        "search_name": "desperados",
        "rarity": "Rare",
        "role": "Wildcard",
        "tier": "S",
        "teammates": ["Inferno", "Big Paku", "Cyber Agent", "Dj Equalizer"],
        "weapon": "Mercy & Wrath",
        "ability": "Bounty Lasso (Hook a friend or foe and pull yourself to their position!)"
    },
    {
        "name": "Andrometa",
        "search_name": "andrometa",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Sparky", "Desperados", "Izuna", "Queen Unicorn"],
        "weapon": "Beam",
        "ability": "Aerial Strike (Jump & slam into ground, dealing area damage!)"
    },
    {
        "name": "Krystal",
        "search_name": "krystal",
        "rarity": "Legendary",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Sparky", "T4NKBOT", "Ark-On", "Dj Equalizer"],
        "weapon": "Ice Hand",
        "ability": "Stalactite Dive (Take a huge leap and hover in the air, Aim at enemies to dive on them, stun them and inflict massive damage!)"
    },
    {
        "name": "Darius",
        "search_name": "darius",
        "rarity": "Common",
        "role": "Center",
        "tier": "B",
        "teammates": ["Hunter", "Lolly Pop", "Lord VR", "Jager"],
        "weapon": "Soccer Ball Launcher",
        "ability": "MVP Flash Tackle (Perform your best tackle move, pushing and dealing damage!)"
    },
    {
        "name": "Izuna",
        "search_name": "izuna",
        "rarity": "Rare",
        "role": "Center",
        "tier": "A",
        "teammates": ["Eagle Eye", "Jaguar", "Oksa", "Mayra"],
        "weapon": "Karasu no yumi",
        "ability": "Yama no seigi (Launches a Spirit bird that go through wall and deals heavy damage!)"
    },
    {
        "name": "Sunny",
        "search_name": "sunny",
        "rarity": "Epic",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Dolb", "Cyber Agent", "Big Paku", "Didi"],
        "weapon": "Double Uzis",
        "ability": "Clone Army Trap (Place multiple hologram traps that stunns and deals damage!)"
    },
    {
        "name": "Jay B",
        "search_name": "jay b",
        "rarity": "Common",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Nad", "Dj Equalizer", "Wave", "Queen Boom"],
        "weapon": "Silent Pistol",
        "ability": "Proxy Mine (Deploy a landmine which explodes when enemies get close!)"
    },
    {
        "name": "Genkis",
        "search_name": "genkis",
        "rarity": "Rare",
        "role": "Camp",
        "tier": "B",
        "teammates": ["Nad", "Shroomy", "Queen Boom", "Sunny"],
        "weapon": "Powder canon",
        "ability": "Fire Grenade (Throw a grenade which creates a fire storm, dealing damage over time to enemies within it!)"
    },
    {
        "name": "Mecha Knight",
        "search_name": "mecha knight",
        "rarity": "Common",
        "role": "Defender",
        "tier": "C",
        "teammates": ["Dan", "Vlad", "Quetza", "Long Shot"],
        "weapon": "Rail Gun",
        "ability": "Shield (Deploy a shield that let you and your allies to shoot through safely!)"
    },
    {
        "name": "Lucha Muerta",
        "search_name": "lucha muerta",
        "rarity": "Epic",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Mayra", "Hannibal", "Cipher", "Rippin Finn"],
        "weapon": "Chainsaw",
        "ability": "Pounce (Pounce and Leave a fart behind which deals poison damage over time!)"
    },
    {
        "name": "Cleo",
        "search_name": "cleo",
        "rarity": "Common",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Inferno", "Cyber Agent", "Cipher", "Sparky"],
        "weapon": "Energy Blast",
        "ability": "Cat Jump (Jump with a short cooldown, and double jump in the air!)"
    },
    {
        "name": "Meduza",
        "search_name": "meduza",
        "rarity": "Epic",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Mayra", "Rick Rock", "Shade", "Queen Boom"],
        "weapon": "Death Ray",
        "ability": "Petrification (Turn yourself into stone, becoming slow but invulnerable!)"
    },
    {
        "name": "Virus",
        "search_name": "virus",
        "rarity": "Common",
        "role": "Camp",
        "tier": "B",
        "teammates": ["Duality", "Laika", "Jay B", "Mekkalodon"],
        "weapon": "The Needle",
        "ability": "Infection (Launches an infected capsule that will stun, slow and inflict damage over time!)"
    },
    {
        "name": "Inferno",
        "search_name": "inferno",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "A",
        "teammates": ["Rick Rock", "Nad", "Nautica", "Marco Polo"],
        "weapon": "Iron Fang",
        "ability": "Claws of Hell (Throws and bring back his claws, pulling any stricken enemies towards him and deals heavy damage!)"
    },
    {
        "name": "Striker",
        "search_name": "striker",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "S",
        "teammates": ["Queen Boom", "T4NKBOT", "Marco Polo", "Rick Rock"],
        "weapon": "Power Balls",
        "ability": "Home Run (Dash near an enemy and swing your bat to send them flying!)"
    },
    {
        "name": "Fragman",
        "search_name": "fragman",
        "rarity": "Epic",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["K.Boom", "Aldric", "Queen Unicorn", "Sunny"],
        "weapon": "Justice Gun",
        "ability": "Super Ultra Power Blaster! (Fires three large destructive beams that igone walls!)"
    },
    {
        "name": "O.K.",
        "search_name": "o.k.",
        "rarity": "Epic",
        "role": "Defender",
        "tier": "C",
        "teammates": ["Mecha Knight", "Lucha Muerta", "Oksa", "Didi"],
        "weapon": "Videobeam",
        "ability": "Static Zone (Deploy a beacon that heals your allies over time, while weakening your opponents!)"
    },
    {
        "name": "Ken Drift",
        "search_name": "ken drift",
        "rarity": "Rare",
        "role": "Center",
        "tier": "B",
        "teammates": ["Imperius", "Pumpkin Pete", "Sparky", "Blue Jaw"],
        "weapon": "Screw-Gun",
        "ability": "Rolling Blaze (Launches fiery tires at his enemies!)"
    },
    {
        "name": "Hunter",
        "search_name": "hunter",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Hannibal", "Duality", "Ao", "Kaz'oolu"],
        "weapon": "Slice & Dice",
        "ability": "Dark Storm (Hunter shoots in every direction, while being slowed and taking reduced damaged for the duration!)"
    },
    {
        "name": "Hannibal",
        "search_name": "hannibal",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Siku", "Shroomy", "SlimeR", "Hunter"],
        "weapon": "Liberty Shield",
        "ability": "Elephant Stomp (Jump, stun, or pull nearby enemies towards you and deal AoE damage to all!)"
    },
    {
        "name": "Duality",
        "search_name": "duality",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "B",
        "teammates": ["Hannibal", "Hunter", "Hubble", "Amelie"],
        "weapon": "The Money-Maker",
        "ability": "Demonic Marking (Switch to your demonic sniper weapon to mark a specific target and get a 3sec speed boost. When the target is Fragged by anyone in the team, you get a Demonic Essence that stacks up to 3 times, giving you a damage boost on both your weapons!)"
    },
    {
        "name": "AO",
        "search_name": "ao",
        "rarity": "Rare",
        "role": "Center",
        "tier": "B",
        "teammates": ["Izuna", "Ollie", "Long Shot", "K.Boom"],
        "weapon": "Rengoku",
        "ability": "Ground Slam (AO slams the ground and send forwards a stone wave, dealing damage and rooting any enemies caught in its path. It explodes after a few seconds dealing massive AoE damage and stunning all enemies in its radius!)"
    },
    {
        "name": "Kaz'oolu",
        "search_name": "kaz'oolu",
        "rarity": "Epic",
        "role": "Defender",
        "tier": "C",
        "teammates": ["Jager", "Hunter", "Shade", "Jaguar"],
        "weapon": "Relic Staff",
        "ability": "Octotems Field (Octotems are summoned in a field all around Kaz'oolu. Each octotem creates a small area which poisons and slows the enemies passing through it!)"
    },
    {
        "name": "Hubble",
        "search_name": "hubble",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "A",
        "teammates": ["Dolb", "Sparky", "Jay B", "Miss J"],
        "weapon": "TurboLazer 1.9.9",
        "ability": "Apollo 9000 (Launches deadly satellites that fires lasers at your enemies!)"
    },
    {
        "name": "Siku",
        "search_name": "siku",
        "rarity": "Common",
        "role": "Camp",
        "tier": "S",
        "teammates": ["MacDyver", "Hannibal", "Oksa", "Cipher"],
        "weapon": "Atlatl Harpoon",
        "ability": "Glacial Pillar (Summon an icy spire to give yourself the high ground and fire powerful harpoons!)"
    },
    {
        "name": "Shroomy",
        "search_name": "shroomy",
        "rarity": "Common",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Evil Piper", "Queen Boom", "Queen Unicorn", "Ken Drift"],
        "weapon": "Spore Sprayer",
        "ability": "Creeping Mold (Launches a circle of creeping vegetation that spreads, strengthening and healing allies and damaging enemies!)"
    },
    {
        "name": "SlimeR",
        "search_name": "slimer",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "C",
        "teammates": ["Dr. Frost", "Dan", "Inferno", "Vlad"],
        "weapon": "Slime Gun",
        "ability": "Slime Being (Spawn a small jelly slime that rushes at any enemy coming close to slow it down!)"
    },
    {
        "name": "Dr. Frost",
        "search_name": "dr. frost",
        "rarity": "Common",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Striker", "Mekkalodon", "Sparky", "Queen Boom"],
        "weapon": "Freezing Gun",
        "ability": "Avalanche (Send a volley of snowballs which deal frost damage over time and slow enemies on Impact!)"
    },
    {
        "name": "Amelie",
        "search_name": "amelie",
        "rarity": "Epic",
        "role": "Center",
        "tier": "C",
        "teammates": ["Nad", "Ollie", "Darius", "Dj Equalizer"],
        "weapon": "Assault Rifle",
        "ability": "Grappling Hook (Launch a grappling hook to reach high places or move faster!)"
    },
    {
        "name": "Quarter-BK",
        "search_name": "quarter-bk",
        "rarity": "Epic",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Nad", "Dunkan", "Dolb", "Smoker"],
        "weapon": "Grenade Launcher",
        "ability": "Tackle (Dash in a straight line, pushing enemies out of the way!)"
    },
    {
        "name": "Baron Voodoom",
        "search_name": "baron voodoom",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "B",
        "teammates": ["Bot Mama", "Ripper", "Queen Boom", "Imperius"],
        "weapon": "Death Stick",
        "ability": "Ressurection (Resurrect all allies in a large area OR revive instantly when you die if your ability is not on Cooldown!)"
    },
    {
        "name": "Shino-B",
        "search_name": "shino-b",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "A",
        "teammates": ["Fragman", "Nautica", "Buck", "Zap Girl"],
        "weapon": "Kunai Gun",
        "ability": "Sidestep (Get telported next to the enemy you aiming and get speed and damage boost!)"
    },
    {
        "name": "Ape-Suit",
        "search_name": "ape-suit",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Dan", "Nad", "Cleo", "Queen Boom"],
        "weapon": "Gatling",
        "ability": "Shredder (Shred through enemies with a high-damage alternate fire!)"
    },
    {
        "name": "Lord VR",
        "search_name": "lord vr",
        "rarity": "Epic",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Ark-On", "Lolly Pop", "Darius", "Redshadow"],
        "weapon": "Bit Phaser",
        "ability": "Copy that! (VR can copy any enemy or ally weapon and supercharge it!)"
    },
    {
        "name": "Prisoner-99",
        "search_name": "prisoner-99",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Izuna", "Buck", "Cyber Cop", "Vandal"],
        "weapon": "Sawgun",
        "ability": "Saw (Fires up to three saws that slice enemies and bounce off walls!)"
    },
    {
        "name": "Smoker",
        "search_name": "smoker",
        "rarity": "Epic",
        "role": "Center",
        "tier": "C",
        "teammates": ["Desperados", "Ron1n", "Ripper", "Detective Guizmo"],
        "weapon": "Smoke Gun",
        "ability": "Smoke Bike (Ride a motorcycle that stuns enemies and leaves a toxic smoke behind it!)"
    },
    {
        "name": "Laika",
        "search_name": "laika",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "A",
        "teammates": ["Rick Rock", "Queen Boom", "Mayra", "Dj Equalizer"],
        "weapon": "Rocket Launcher",
        "ability": "Thrusters (Jump in the air and start gliding! You can shoot while airborne!)"
    },
    {
        "name": "Scout & Nutty",
        "search_name": "scout & nutty",
        "rarity": "Epic",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Baron Vodom", "Buck", "Oksa", "Laika"],
        "weapon": "Nut Pistol",
        "ability": "Turret Spawn (Spawn 2 turrets that defend the bunkers!)"
    },
    {
        "name": "Vandal",
        "search_name": "vandal",
        "rarity": "Common",
        "role": "Center",
        "tier": "B",
        "teammates": ["Izuna", "Marco Polo", "Rick Rock", "Cactarina"],
        "weapon": "Spray Gun",
        "ability": "Paint Bomb (Throw a paint bomb that deals damage and explodes on contact, spreading paint that slows and weakens!)"
    },
    {
        "name": "Buck",
        "search_name": "buck",
        "rarity": "Rare",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Vandal", "Redshadow", "Wave", "Dolb"],
        "weapon": "Nature's Fury",
        "ability": "Log (Throws a lag of woods forward, damaging and hurling enemies into the air!)"
    },
    {
        "name": "Rolaf",
        "search_name": "rolaf",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "B",
        "teammates": ["Cipher", "General mekk", "Sunny", "Dolb"],
        "weapon": "Neo-Mjolnir",
        "ability": "Thunderstrike (Throws a giant electic hammer forward, stunning enemies and damaging with lightning bolts. The hammer when returns, damaging enemies again, and triggers a final thunder strike that stuns enemies around Rolaf!)"
    },
    {
        "name": "Hades5.1",
        "search_name": "hades5.1",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Mayra", "Dj Equalizer", "Queen Boom", "Wave"],
        "weapon": "Holo Scythe",
        "ability": "TROJAN.EXE (Infects enemies around you, dealing damage over time!)"
    },
    {
        "name": "Rippin'Finn",
        "search_name": "rippin finn",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "B",
        "teammates": ["Dan", "Inferno", "Virus", "Cleo"],
        "weapon": "Beach Blaster",
        "ability": "Tidal Wave (Launches a gnarly wave and pushes enemy it encounter, briefly stunning them!)"
    },
    {
        "name": "GigaGoo",
        "search_name": "gigagoo",
        "rarity": "Legendary",
        "role": "Defender",
        "tier": "S",
        "teammates": ["Desperados", "Blot", "Cyber Agent", "C.O.B.R.A."],
        "weapon": "The Gooper",
        "ability": "Ka-BOOM! (Explodes into tiny slimes which he can collect to get some health points back. The explosion also deals damage!)"
    },
    {
        "name": "Bobbler",
        "search_name": "bobbler",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Blue Jaw", "Sunny", "Piper Reese", "General Mekk"],
        "weapon": "The Bubble Bobble",
        "ability": "Ultimate Bubble!! (Shoots a bubble that follows the initial target and stuns the first enemy caught in it! The BUBBLED enemy starts rising and takes reduced damaged!)"
    },
    {
        "name": "Miss Bunny",
        "search_name": "miss bunny",
        "rarity": "Legendary",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["The Boss", "Laika", "Wolfson", "Nad"],
        "weapon": "Carrot Blaster",
        "ability": "Bunny Hop! (Plant an explosive carrot in the ground which propels you forward when exploding. This can stack up to three times!)"
    },
    {
        "name": "Scrapper",
        "search_name": "scrapper",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "A",
        "teammates": ["Imperius", "Soldatron", "Cactarina", "Sparky"],
        "weapon": "Scrap Dispenser",
        "ability": "Fix It Up! (Uses its builder skills to repair a bunker/tower!)"
    },
    {
        "name": "Fraggenstein",
        "search_name": "fraggenstein",
        "rarity": "Epic",
        "role": "Center",
        "tier": "C",
        "teammates": ["Dunkan", "T4NKBOT", "Marco Pollo", "Ron1n"],
        "weapon": "Blunderbuster",
        "ability": "IT'S ALIIIIIVE!! (He overcharges himself with electricity, granting him additional HP, Speed and Fire Rate, as well as dealing electric damages to nearby enemies!)"
    },
    {
        "name": "Queen Boom",
        "search_name": "queen boom",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "S",
        "teammates": ["T4NKBOT", "Striker", "Marco Pollo", "Didi"],
        "weapon": "BoomBox",
        "ability": "Noise Barrier Boost! (Gives you a bit of extra HP, while all the allies in front of you get even more and gain a speed boost!)"
    },
    {
        "name": "Wolfson",
        "search_name": "wolfson",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Buck", "Miss Bunny", "Bobbler", "Rippin Finn"],
        "weapon": "Digital claws",
        "ability": "Bloodthirst (Allows Wolfson to see through walls and get bonus movement speed for every character below 50% HP!)"
    },
    {
        "name": "Mekkalodon",
        "search_name": "mekkalodon",
        "rarity": "Legendary",
        "role": "Camp",
        "tier": "B",
        "teammates": ["Blue Maw", "Sunny", "Sombrero", "Noot"],
        "weapon": "Holo-Harpoon",
        "ability": "Shark Storm! (Become a living shark-nado! Enemies caught will be pushed in the air and take damage every second!)"
    },
    {
        "name": "Ollie",
        "search_name": "ollie",
        "rarity": "Legendary",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Amelie", "Jab", "Mr. Tiger", "The Boss"],
        "weapon": "Retro Blasters",
        "ability": "Hoverboard (Travels with the hoverboard in the range through the without falling!)"
    },
    {
        "name": "Soldatron",
        "search_name": "soldatron",
        "rarity": "Epic",
        "role": "Camp",
        "tier": "A",
        "teammates": ["Queen Unicorn", "Sparky", "Desperados", "Cleo"],
        "weapon": "Pneumatic Blaster",
        "ability": "Ready! Aim! FIRE! (Aim at an area and shoot your head like a mortar!)"
    },
    {
        "name": "Cactarina",
        "search_name": "cactarina",
        "rarity": "Common",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Mayra", "Dj Equalizer", "Big Paku", "Ark-On"],
        "weapon": "Prickler",
        "ability": "Cact-Trap (Lays a predator plant that springs on the first enemy to walk over it!)"
    },
    {
        "name": "The Boss",
        "search_name": "the boss",
        "rarity": "Legendary",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Hades5.1", "Lilli", "Noot", "Jaw Jaw"],
        "weapon": "Money Gun",
        "ability": "Rainin' Bullets! (Deploys 3 robot mobsters who shoot down everything in front of them, slowing enemies caught!)"
    },
    {
        "name": "Fidelio",
        "search_name": "fidelio",
        "rarity": "Common",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Dan", "Shade", "Jaguar", "Blaise"],
        "weapon": "Nailcannon",
        "ability": "The Pain Machine! (Spawns a turret that shoot nails. Fidelio can mount it to unleash the power of the double nailgatling!)"
    },
    {
        "name": "Dunkan",
        "search_name": "dunkan",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Evil Piper", "Cyber Agent", "Aldric", "Freez-B"],
        "weapon": "Fire throw",
        "ability": "Slam Dunk (Throws a ball that stuns enemies and jump into the air to slam dunk them for lots of damage!)"
    },
    {
        "name": "T4NKBOT",
        "search_name": "t4nkbot",
        "rarity": "Epic",
        "role": "Center",
        "tier": "S",
        "teammates": ["Striker", "Nad", "Inferno", "Cleo"],
        "weapon": "Registered BOT-113 Ammo",
        "ability": "T4NK Mode (Take your full tank form, firing heavy missiles and gaining a health & speed boost!)"
    },
    {
        "name": "Sombrero",
        "search_name": "sombrero",
        "rarity": "Epic",
        "role": "Camp",
        "tier": "C",
        "teammates": ["Cyber Agent", "Big Paku", "Hubble", "Hunter"],
        "weapon": "Revenge Rifle",
        "ability": "Curse of the dead (Curse the enemy team for 10s, causing 2 death specters to spawn whenever someone in your team kills an opponent. The specters then fly towards enemy bunkers, exploding on the impact - or when killed by an enemy!)"
    },
    {
        "name": "Marco Pollo",
        "search_name": "marco pollo",
        "rarity": "Epic",
        "role": "Defender",
        "tier": "S",
        "teammates": ["Striker", "Rick Rock", "Queen Boom", "T4NKBOT"],
        "weapon": "The Meat Blaster",
        "ability": "Pasta la Vista! (Throw a ball of spaghetti that deals damage, stuns enemies and push them while rolling on the ground!)"
    },
    {
        "name": "Ark-On",
        "search_name": "ark-on",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Imperius", "Krystal", "Detective Guizmo", "Queen Unicorn"],
        "weapon": "Power Charge",
        "ability": "Wrath of Ark-On (Dash and levitate over the battlefield creating a thunder storm and shoots 3 lightning bolts at the center of the storm to damage your opponents!)"
    },
    {
        "name": "Zap Girl",
        "search_name": "zap girl",
        "rarity": "Legendary",
        "role": "Camp",
        "tier": "A",
        "teammates": ["Oksa", "Bibi", "Nad", "Dj Equalizer"],
        "weapon": "The Zapper!",
        "ability": "Zap Girl's Tower (Deploy an electrically charged tower that slows down enemy zap-zap-zaps everyone around for lots of constant damage!)"
    },
    {
        "name": "Redshadow",
        "search_name": "redshadow",
        "rarity": "Epic",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Cipher", "Mayra", "Ripper", "Big Paku"],
        "weapon": "Double Laser Sword",
        "ability": "Red Star (Throws his laser sword like a boomerang towards a nearby enemy. If hits, he teleports behind his target and deals heavy damage!)"
    },
    {
        "name": "Lilli",
        "search_name": "lilli",
        "rarity": "Legendary",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Gigagoo", "Boomi", "MacDyver", "Jager"],
        "weapon": "Hell of a stick",
        "ability": "Cyber Rage (Turns into a burning lava ball and releas it in an explosion of flames, the longer you wait for the charge, the more damage you deal!)"
    },
    {
        "name": "Jager",
        "search_name": "jager",
        "rarity": "Legendary",
        "role": "WildCard",
        "tier": "A",
        "teammates": ["Sunny", "Izuna", "Dolb", "Jab"],
        "weapon": "Ectoplasma Bolter",
        "ability": "Release the Specters! (Release 3 specters, they'll automatically chase enemies, exploding after a while, causing damage and healing Jager!)"
    },
    {
        "name": "Noot",
        "search_name": "noot",
        "rarity": "Common",
        "role": "Center",
        "tier": "B",
        "teammates": ["Darius", "Lord VR", "Strix", "Mei Long"],
        "weapon": "Snowball Canons",
        "ability": "South Pole Blizzard (He triggers a blizzard zone around him. Enemies are slowed down by the cold until they are frozen in place in a big ice cube!)"
    },
    {
        "name": "Strix",
        "search_name": "strix",
        "rarity": "Epic",
        "role": "Center",
        "tier": "C",
        "teammates": ["Vandal", "Striker", "MacDyver", "Marco Pollo"],
        "weapon": "Dark claws",
        "ability": "Frozen mist (Sends a frozen mist in front of him which slows enemies then stuns them if they stay in it. The more you charge the ability the bigger the mist will be!)"
    },
    {
        "name": "Mayra",
        "search_name": "mayra",
        "rarity": "Legendary",
        "role": "Camp",
        "tier": "C",
        "teammates": ["Big Paku", "Hunter", "Cyber Agent", "Poca Hunter"],
        "weapon": "Killer bees",
        "ability": "Api-harmoney (Propel into the air, shoot with all your bees at the same time and hover until you reach the ground!)"
    },
    {
        "name": "Detective Guizmo",
        "search_name": "detective guizmo",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Jack & Timmy", "Dolb", "Cheryl", "Andrometa"],
        "weapon": "Not-so-regular gun",
        "ability": "Trick master (Grab your enemy. Then take a pic of them from really close, blinding them. Then set them aside. Repeat!)"
    },
    {
        "name": "Jaw Jaw",
        "search_name": "jaw jaw",
        "rarity": "Rare",
        "role": "Center",
        "tier": "C",
        "teammates": ["Zap Girl", "Ark-On", "Lolly Pop", "Dj Equalizer"],
        "weapon": "Rescue board",
        "ability": "Reef Break (He start surfing on his board forward, pushing, slowing and damaging all the enemies he encounters!)"
    },
    {
        "name": "MacDyver",
        "search_name": "macdyver",
        "rarity": "Epic",
        "role": "Center",
        "tier": "B",
        "teammates": ["Cipher", "Blot", "Hunter", "Darius"],
        "weapon": "Fluger FLY-44",
        "ability": "Brrrrrrrrrrr (Takes off and swoops down from the sky, raining rapid-fire bullets down on all those in front of him!)"
    },
    {
        "name": "Pumpkin Pete",
        "search_name": "pumpkin pete",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Queen Unicorn", "Cipher", "Mei Long", "Hakuryu"],
        "weapon": "Lantern Laser",
        "ability": "Hallow Hush (Becoms a swarm of crows, before reappearing in a zone of silence and attacking opponents with its slowing beam!)"
    },
    {
        "name": "Mei Long",
        "search_name": "mei long",
        "rarity": "Epic",
        "role": "Defender",
        "tier": "S",
        "teammates": ["Nad", "Sparky", "Queen Boom", "Striker"],
        "weapon": "Precision Palette",
        "ability": "Chain of Color (Throws a chain that slows down the stricken enemies, making them more vulnerable to damage. Opponents are stunned if they fail to leave the area within 3 seconds!)"
    },
    {
        "name": "Imperius",
        "search_name": "imperius",
        "rarity": "Legendary",
        "role": "Center",
        "tier": "A",
        "teammates": ["Splashy", "Debby", "Bob", "Jager"],
        "weapon": "Obscure charge",
        "ability": "Divine Storm (Jumps and levitate above the battlefield, channeling electrical energy and launching lightning bolts at any enemy he can see!)"
    },
    {
        "name": "Splashy",
        "search_name": "splashy",
        "rarity": "Epic",
        "role": "Center",
        "tier": "B",
        "teammates": ["Bob", "Dr. Crow", "Blue Jaw", "Jaw Jaw"],
        "weapon": "Hydro Pulse",
        "ability": "Tactical Sublimation (Ice Golems creates a damaging and slowing explosion, Splashy equips a shotgun. Gaseous space creates an explosion that repels, Splashy becomes invulnerable and gets a boost!)"
    },
    {
        "name": "Aldric",
        "search_name": "aldric",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["K. Boom", "Ellen", "Blaise", "Lucha Muerta"],
        "weapon": "Enchanted Grimoire",
        "ability": "Arcane Mastery (Aldric's Grimoire absorbs damage inflicted and energy from defeated FRAGGERS to evolve the appearance and effects of its spell. The higher the required number of eliminations, the more ns, the more powerful the ability becomes!)"
    },
    {
        "name": "Miss J",
        "search_name": "miss j",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "C",
        "teammates": ["Cyber Agent", "Didi", "Dj Equalizer", "Miss Bunny"],
        "weapon": "Plasma Launcher MKII",
        "ability": "Turbo Glider (Super buffed Jet pack that Miss J uses to fly over the map, don't forget to refuel it!)"
    },
    {
        "name": "Bot Mama",
        "search_name": "bot mama",
        "rarity": "Epic",
        "role": "Defender",
        "tier": "C",
        "teammates": ["Baron Voodoom", "Vandal", "Cleo", "Dan"],
        "weapon": "Nail Gun",
        "ability": "Bot Spawn (Spawn a robot which defends the bunkers, with a maximum of 2 robots at once!)"
    },
    {
        "name": "Freez-B",
        "search_name": "freez-b",
        "rarity": "Epic",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["The Boss", "Oksa", "Hannibal", "Sunny"],
        "weapon": "Disc launcher",
        "ability": "Rush (Increases her movement speed for a short time, stunning any enemies she runs into!)"
    },
    {
        "name": "Jack El Padre",
        "search_name": "jack el padre",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Inferno", "Sparky", "Lilli", "General Mekk"],
        "weapon": "Shotgun",
        "ability": "Grenade (Throw a grenade that deals damage on impact!)"
    },
    {
        "name": "Eagle Eye",
        "search_name": "eagle eye",
        "rarity": "Common",
        "role": "Camp",
        "tier": "A",
        "teammates": ["Izuna", "Desperados", "Nad", "Dj Equalizer"],
        "weapon": "Explosive Arrow",
        "ability": "Zoom (Zoom at medium range!)"
    },
    {
        "name": "Cyber Girl",
        "search_name": "cyber girl",
        "rarity": "Rare",
        "role": "Wildcard",
        "tier": "C",
        "teammates": ["Meduza", "Virus", "Hubble", "Stella"],
        "weapon": "Submachine Gun",
        "ability": "Teleport (On the 1st use Cyber girl will plant a tag on the ground. On the 2nd use, Cyber Girl will teleport back to where the tag was planted, while receiving several boosts!)"
    },
    {
        "name": "Volcano",
        "search_name": "volcano",
        "rarity": "Legendary",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Freez-B", "Dan", "Sunny", "Marco Pollo"],
        "weapon": "Lava Launcher",
        "ability": "Magma Ball (Channel a huge magma ball that sticks to walls and deals tremendous damage!)"
    },
    {
        "name": "Quetza",
        "search_name": "quetza",
        "rarity": "Common",
        "role": "Center",
        "tier": "A",
        "teammates": ["Striker", "Siku", "Big Paku", "Genkis"],
        "weapon": "Double SMG",
        "ability": "Dodgeball (Throw a ball which pushes enemies far back!)"
    },
    {
        "name": "Vlad",
        "search_name": "vlad",
        "rarity": "Rare",
        "role": "Camp",
        "tier": "S",
        "teammates": ["Cleo", "Quarter Bk", "Nad", "Hubble"],
        "weapon": "Sniper Rifle",
        "ability": "Tornado (Create a tornado sending enemies up in the air! When they hit the ground, they are stunned and slowed down!)"
    },
    {
        "name": "Cyber Cop",
        "search_name": "cyber cop",
        "rarity": "Rare",
        "role": "Center",
        "tier": "B",
        "teammates": ["Izuna", "Vandal", "Marco Pollo", "Andrometa"],
        "weapon": "Justice Gun",
        "ability": "Jail (Deploys a barred wall that burns enemies to death if they run through it!)"
    },
    {
        "name": "Captain Polar",
        "search_name": "captain polar",
        "rarity": "Epic",
        "role": "Camp",
        "tier": "B",
        "teammates": ["Poca Hunter", "Miss Bunny", "Dan", "Ark-On"],
        "weapon": "Recon Rifle",
        "ability": "Polar Freeze (His bullets apply stacks of Polar Freeze to his targets. The 3rd stack freezes for 3 seconds and deals additional damage!)"
    },
    {
        "name": "Valkia",
        "search_name": "valkia",
        "rarity": "Common",
        "role": "Center",
        "tier": "C",
        "teammates": ["Blaise", "Evil Piper", "Inferno", "Hunter"],
        "weapon": "Light Bringer",
        "ability": "Ascend! (Jump in the air, become invulnerable, and fire a powerful beam to punish your foes!!)"
    },
    {
        "name": "Sogeki-Chan",
        "search_name": "sogeki-chan",
        "rarity": "Rare",
        "role": "Camp",
        "tier": "A",
        "teammates": ["Dr. Crow", "Siku", "Zap Girl", "T4NKBOT"],
        "weapon": "Enkei",
        "ability": "Orbital Strike! (Slows down to lock enemies in the open, then blasts targeted enemies!)"
    },
    {
        "name": "Bibi",
        "search_name": "bibi",
        "rarity": "Epic",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Fragman", "Gigagoo", "Queen Boom", "Wyatt"],
        "weapon": "T-Shirt Cannon",
        "ability": "Go BiBi Go! (Cheer on your teammates, healing them and increasing their speed in a radius!)"
    },
    {
        "name": "Mr.Tiger",
        "search_name": "mr. tiger",
        "rarity": "Legendary",
        "role": "Camp",
        "tier": "S",
        "teammates": ["Sergeant Crusher", "Cipher", "Nad", "Cleo"],
        "weapon": "Double 24k",
        "ability": "Chopper Call (Mr.Tiger calls in a favor in the form of an airstrike!Target an area and 5 strikes will follow!)"
    },
    {
        "name": "Sno",
        "search_name": "sno",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Mayra", "Jay B", "Hannibal", "C.O.B.R.A."],
        "weapon": "Gauntlet Blasters",
        "ability": "Ski Free! (Get on your skis and dash! The more in the guage is filled, the longer the ability will be!)"
    },
    {
        "name": "Hakuryu",
        "search_name": "hakuryu",
        "rarity": "Epic",
        "role": "Center",
        "tier": "A",
        "teammates": ["Cipher", "Freez-B", "Sparky", "Jaguar"],
        "weapon": "Kuchiku",
        "ability": "Unleash the Dragon! (He collects the energy of fragges he defeats and uses it to contain various buffs, the power of which depends on the amount of energy he stores!)"
    },
    {
        "name": "Mr. Doe",
        "search_name": "mr. doe",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "C",
        "teammates": ["Eagle Eye", "Cyber Cop", "Mimi", "Ron1n"],
        "weapon": "Tommy Gun",
        "ability": "Invisibility (Turn invisible, gaining a speed boost but but disabling autoshoot. Ends on damage, crowd control, or manually. Manually ending it grants a damage boost!)"
    },
    {
        "name": "Avalanche",
        "search_name": "avalanche",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Krystal", "Strix", "Noot", "Sno"],
        "weapon": "Icicle Blaster",
        "ability": "Ice Prison! (Shoots a stalactite that spawns an ice prison, dealing damage and trapping anyone caught in it!)"
    },
    {
        "name": "Nautica",
        "search_name": "nautica",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Ripper", "Dj Equalizer", "Vandal", "Cyber Agent"],
        "weapon": "Tech-Trident",
        "ability": "Go Leviathan!! (She sends her pet orca, Leviathan, to damage and push away every enemy marked!)"
    },
    {
        "name": "General Mekk",
        "search_name": "general mekk",
        "rarity": "Epic",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Sunny", "Nad", "Queen Unicorn", "Shroomy"],
        "weapon": "Mekk-chine Gun",
        "ability": "Deploy Drone (Deploys your Drone to attack enemies, slowing them and making them more vulnerable!)"
    },
    {
        "name": "RON1N",
        "search_name": "ron1n",
        "rarity": "Epic",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Ripper", "Andrometa", "Hunter", "Inferno"],
        "weapon": "Hakai no Ken",
        "ability": "Swift Strike (A dash that deals damage to enemies caught in the trajectory. The Cooldown decreases after a kill!)"
    },
    {
        "name": "Dr. Crow",
        "search_name": "dr. crow",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Blue Jaw", "MacDyver", "Hakuryu", "Pumpkin Pete"],
        "weapon": "Vials Launcher",
        "ability": "Mode Switch (Switches between poison mode and heal mode!)"
    },
    {
        "name": "Mimi",
        "search_name": "mimi",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "A",
        "teammates": ["Jay B", "Takeshi", "T4NKBOT", "Laika"],
        "weapon": "Mimic",
        "ability": "A Real Fake Wall (Deploys a large wall that your enemies cannot pass through! However, they can shoot to destroy it!)"
    },
    {
        "name": "Takeshi",
        "search_name": "takeshi",
        "rarity": "Common",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Virus", "Stella", "Lucha Muerta", "Jaw Jaw"],
        "weapon": "RCSP-4",
        "ability": "Overclock (Trigger your robot's secret power source to activate overclock mode for a few seconds, giving you a health and speed boost while throwing punches at everyone facing you!)"
    },
    {
        "name": "Stella",
        "search_name": "stella",
        "rarity": "Rare",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Wave", "K. Boom", "Bob", "Blaise"],
        "weapon": "Witch Broom 2.0",
        "ability": "Ascending Star (Jump on your broom to fly around the map as you please and shoot stars at your opponents!)"
    },
    {
        "name": "Wave",
        "search_name": "wave",
        "rarity": "Epic",
        "role": "Center",
        "tier": "A",
        "teammates": ["Mr. Tiger", "Genkis", "Hunter", "Miss J"],
        "weapon": "DJ Beam",
        "ability": "Sound Blaster (Sends a sonic wave trapping opponents long enough for the sound to travel through their body and then explodes when he hits a beat after 2 seconds or when 2 or more enemies are in close range!)"
    },
    {
        "name": "K. Boom",
        "search_name": "k. boom",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Detective Guizmo", "Fragman", "Ellen", "Nautica"],
        "weapon": "Adaptarsenal",
        "ability": "Quick Swap (K.Boom's main weapon changes from a rotation of 3: rifle, shotgun and rocket launcher!)"
    },
    {
        "name": "Bob",
        "search_name": "bob",
        "rarity": "Rare",
        "role": "Defender",
        "tier": "A",
        "teammates": ["Dr. Crow", "Jager", "Pumpkin Pete", "Hannibal"],
        "weapon": "Cosmic Blaster",
        "ability": "Stellar Attraction (Throws a beacon that creates a zone on the ground, slowing and preventing enemies from using weapons and abilities. After a few seconds, any enemies present are drawn into the air!)"
    },
    {
        "name": "Blaise",
        "search_name": "blaise",
        "rarity": "Rare",
        "role": "Camp",
        "tier": "S",
        "teammates": ["Blot", "Gabie & Peanut", "Blaise", "Rick Rock"],
        "weapon": "Pyro-Gun",
        "ability": "Explosive Fire (Shoots a fiery bullet that explodes on impact. If it hits a flaming trap, the trap detonates, causing additional damage!)"
    },
    {
        "name": "Bonk",
        "search_name": "bonk",
        "rarity": "Epic",
        "role": "Center",
        "tier": "C",
        "teammates": ["Ellen", "Inferno", "Queen Boom", "K. Boom"],
        "weapon": "Bonk?",
        "ability": "Bonk! (With a comedic honk, a massive boxer's fist rockets from Bonk weapon, delivering a solid blow that will knock back opponents!)"
    },
    {
        "name": "Ellen",
        "search_name": "ellen",
        "rarity": "Common",
        "role": "Center",
        "tier": "B",
        "teammates": ["Piper Reese", "Jab", "Pumpkin Pete", "Sparky"],
        "weapon": "Fury",
        "ability": "Clearshot (Clearshot gives Ellen the ability to target enemies, hidden behind walls, but it cannot damage bunkers!)"
    },
    {
        "name": "Wyatt",
        "search_name": "wyatt",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "S",
        "teammates": ["Blaise", "Big Paku", "Jab", "Evil Piper"],
        "weapon": "Cyber colt.44",
        "ability": "Yee-Haw! (His damage and fire rate spike for a short time, locking onto the nearest target and instantly switching if it's eliminated or out of sight!)"
    },
    {
        "name": "BlueMaw",
        "search_name": "bluemaw",
        "rarity": "Epic",
        "role": "Wildcard",
        "tier": "S",
        "teammates": ["Dj Equalizer", "Hannibal", "Big Paku", "Nad"],
        "weapon": "Harpuzi",
        "ability": "Marine Crash (A shielded bike appears, giving speed and resistance. Collisions launch Bluemaw into the air as the bike explodes, dealing damage and knockback. Possible to Jump off early, sending the bike forward to explode on impact!)"
    },
    {
        "name": "Gabie & Peanut",
        "search_name": "gabie & peanut",
        "rarity": "Legendary",
        "role": "Defender",
        "tier": "B",
        "teammates": ["Sparky", "Sunny", "Blot", "Mei Long"],
        "weapon": "Tidepiercer",
        "ability": "Peanut's Pew Pew Perch (Gabie drops a massive anchor from the sky, dealing damage and stunning enemies on impact, those caught at the center take even more! Her monkey, Peanut, clings to the top, wildly firing at nearby foes. While the anchor remains, it slows all enemies in the area!)"
    },
    {
        "name": "Ripper",
        "search_name": "ripper",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "A",
        "teammates": ["Nautica", "Debby", "Lucha Muerta", "Queen Unicorn"],
        "weapon": "Blade Barrage",
        "ability": "Maniac Dance (He dashes at his target, dealing damage upon impact and stunning the enemy for a short duration. Every elimination reduces its cooldown!)"
    },
    {
        "name": "C.O.B.R.A.",
        "search_name": "c.o.b.r.a.",
        "rarity": "Epic",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Miss J", "Shade", "Wyatt", "Desperados"],
        "weapon": "Viper fangs",
        "ability": "Tactical Tumble (She Swiftly rolls in a chosen direction, deploying tactical smoke grenades that shroud her invisibility. The Smokescreen enhances her and nearby allies for a short duration, while severely imparing enemy vision!)"
    },
    {
        "name": "Debby",
        "search_name": "debby",
        "rarity": "Rare",
        "role": "Wildcard",
        "tier": "B",
        "teammates": ["Marco Pollo", "Vandal", "Buck", "Freez-B"],
        "weapon": "Gravity Gloves",
        "ability": "They see me rolling (She jumps and starts rollerskating on a holographic track over the arena. While she's in the air, she triggers exlosions below her, damaging, pushing, and stunning nearby enemies!)"
    },
    {
        "name": "Crimson Guardian",
        "search_name": "crimson guardian",
        "rarity": "Common",
        "role": "Center",
        "tier": "B",
        "teammates": ["Bob", "Bobbler", "MacDyver", "APE-Suit"],
        "weapon": "Sentinel Beam",
        "ability": "Missile Storm (Unleashes a burst of guided missiles from your back, each locking onto nearby enemies in front of you. Missiles follow a straight path and explode on impact, dealing area damage. Best used in open!)"
    },
    {
        "name": "Boomi",
        "search_name": "boomi",
        "rarity": "Legendary",
        "role": "Wildcard",
        "tier": "A",
        "teammates": ["Jay B", "Oksa", "Hades5.1", "Miss J"],
        "weapon": "Bubblegum Bomber",
        "ability": "Sticky Mine (Throws a landmine that sticks to whatever it hits, be it a wall or an allied fragger. Stays in place until an enemy runs into it, or you decide to detonate it!)"
    },
    {
        "name": "Shade",
        "search_name": "shade",
        "rarity": "Epic",
        "role": "Camp",
        "tier": "A",
        "teammates": ["Wyatt", "Nad", "Zap Girl", "Oksa"],
        "weapon": "Raptor Rifle",
        "ability": "Owl Eye (He calls in their owl, Ullu, who flies over the arena and marks the enemies it sees. Marked enemies receive more damage and are visible through walls, even by Shade's allies!)"
    },
    {
        "name": "Sergeant Crusher",
        "search_name": "sergeant crusher",
        "rarity": "Epic",
        "role": "Center",
        "tier": "C",
        "teammates": ["Cyber Agent", "Big Paku", "Queen Boom", "Striker"],
        "weapon": "Plasma Flail",
        "ability": "Selenite Shield (Allies take less damage whenever they're around Sergeant Crusher. Moreover, when his ability is activated, the zone around Sergeant Crusher becomes a shield that enemy projectiles cannot enter!)"
    },
    {
        "name": "Oksa",
        "search_name": "oksa",
        "rarity": "Rare",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["Jaw Jaw", "Mayra", "Dj Equalizer", "Ark-On"],
        "weapon": "Skeggoxen",
        "ability": "Maelstrom (This whirlwind of destruction clears the way with strong damage and pushback effect!)"
    },
    {
        "name": "Jaguar",
        "search_name": "jaguar",
        "rarity": "Common",
        "role": "Attacker",
        "tier": "B",
        "teammates": ["General Mekk", "Dolb", "Hunter", "Inferno"],
        "weapon": "Thunderbolt Thrower",
        "ability": "Power-Pop! (That can packs a punch! Jaguar gets so energized he pushes back nearby enemies in a burst of electricity, heals himself and moves faster for a few seconds!)"
    }
]




COUNTER_MAP = {
        "nad": ["DJ Equalizer", "Evil Piper", "Ripper"],
        "sparky": ["Wyatt", "Queen Unicorn", "Blaise"],
        "cyber agent": ["Desperados", "Sparky", "Rick Rock"],
        "jack & timmy": ["Long Shot", "Genkis", "Big Paku"],
        "dolb": ["Rippin Finn", "Big Paku", "Cipher"],
        "wyatt": ["DJ Equalizer", "Rick Rock", "Rippin Finn"],
        "cleo": ["Nad", "Desperados", "DJ Equalizer"],
        "big paku": ["Nad", "Cyber Agent", "Sogeki chan"],
        "gigagoo": ["Blot", "Wyatt", "Ken Drift"],
        "evil piper": ["Rick Rock", "Piper Reese", "Rippin Finn"],
        "didi": ["Nad", "Cipher", "Cheryl"],
        "cheryl": ["PocaHunter", "Long Shot", "Krystal"],
        "jab": ["DesperaDOS", "Jay B", "Big Paku"],
        "lolly pop": ["Rick Rock", "Andrometa", "Inferno"],
        "queen unicorn": ["Evil Piper", "Nad", "DJ Equalizer"],
        "piper reese": ["Long Shot", "Vlad", "Wyatt"],
        "dj equalizer": ["Blaise", "Rick Rock", "Pocahunter"],
        "blot": ["Bob", "Darius", "Siku"],
        "cipher": ["Ripper", "Lolly Pop", "DJ Eqalizer"],
        "long shot": ["Andrometa", "Wyatt", "Cyber Agent"],
        "rick rock": ["Cipher", "Inferno", "Krystal"],
        "pocahunter": ["Izuna", "Blot", "Big Paku"],
        "desperados": ["Wave", "Boomi", "Gigagoo"],
        "andrometa": ["Rippin Finn", "Detective Guizmo", "Vandal"],
        "krystal": ["Meduza", "Imperius", "DJ Equalizer"],
        "darius": ["Rick Rock", "Marco Pollo", "Virus"],
        "izuna": ["Lord VR", "Desperados", "Ark On"],
        "sunny": ["Buck", "Genkis", "Inferno"],
        "jay b": ["Striker", "Dunkan", "Didi"],
        "genkis": ["C.O.B.R.A.", "Debby", "Rippin Finn"],
        "mecha knight": ["FragMan", "Izuna", "Ellen"],
        "lucha muerta": ["Oksa", "Jack EL Padre", "Zap Girl"],
        "meduza": ["Desperados", "Inferno", "Rick Rock"],
        "virus": ["Duality", "Vlad", "Piper Reese"],
        "inferno": ["Ripper", "Crimson Guardian", "Mayra"],
        "striker": ["Miss J", "Nad", "AO"],
        "fragman": ["Ripper", "Ken Drift", "Ark On"],
        "o.k.": ["Duality", "Dan", "Virus"],
        "hunter": ["Darius", "Marco Pollo", "Hubble"],
        "hannibal": ["Rippin Finn", "Izuna", "Nad"],
        "duality": ["Dunkan", "Mei Long", "Noot"],
        "ao": ["Shroomy", "Striker", "Dolb"],
        "kazoolu": ["Jager", "Izuna", "Captain Polar"],
        "hubble": ["Piper Reese", "Desperados", "Jager"],
        "siku": ["Virus", "Rippin Finn", "Ripper"],
        "shroomy": ["Cactarina", "Andrometa", "Blaise"],
        "slimer": ["Freez-B", "Hakuryu", "Wolfson"],
        "dr.frost": ["Pumpkin Pete", "Mr.Frost", "Laika"],
        "jet": ["Wave", "Cipher", "Shino-B"],
        "amelie": ["Quarter-BK", "Vandal", "Wave"],
        "quarter-bk": ["Nad", "Sparky", "Gigagoo"],
        "baron voodoom": ["Shino-B", "Sno", "BibiTM"],
        "shino-b": ["Rolaf", "Mei Long", "Mr.Tiger"],
        "ape-suit": ["Dan", "Cleo", "Prisoner-99"],
        "lord vr": ["Detective Guizmo", "Big Paku", "Dunkan"],
        "prisoner-99": ["Izuna", "Dr.Crow", "Virus"],
        "smoker": ["Freez-B", "Cleo", "Rippin Finn"],
        "laika": ["DJ Equalizer", "Detective Guizmo", "Ripper"],
        "scout & nutty": ["Hannibal", "Pumpkin Pete", "Buck"],
        "vandal": ["Izuna", "Marco Pollo", "Cyber Cop"],
        "buck": ["DJ Equalizer", "Izuna", "Queen Boom"],
        "rolaf": ["Sno", "RedShadow", "Jager"],
        "hades5.1": ["Sparky", "Bibi", "Queen Boom"],
        "rippin finn": ["Nad", "Cleo", "Krystal"],
        "bobbler": ["Meduza", "Crimson Guardian", "Debby"],
        "miss bunny": ["Andrometa", "Desperados", "Mr.Tiger"],
        "scrapper": ["T4NKBOT", "Jager", "MacDyver"],
        "fraggenstein": ["Big Paku", "Cactarina", "The Boss"],
        "queen boom": ["Cipher", "Inferno", "Nad"],
        "wolfson": ["Hades5.1", "Volcano", "Jay B"],
        "mekkalodon": ["Bob", "Dan", "K. Boom"],
        "ollie": ["Striker", "Mei Long", "Quetza"],
        "soldatron": ["Blue Maw", "Blaise", "Siku"],
        "cactarina": ["Shade", "Jaguar", "Nautica"],
        "the boss": ["Vandal", "Dunkan", "Mayra"],
        "fidelio": ["Nad", "Inferno", "Strix"],
        "dunkan": ["Aldric", "Mei Long", "Mimi"],
        "tankbot": ["Big Paku", "Lilli", "Wave"],
        "sombrero": ["Nad", "Dan", "Sunny"],
        "marco pollo": ["Virus", "Bluemaw", "Vandal"],
        "ark-on": ["DJ Equalizer", "Desperados", "Ripper"],
        "zap girl": ["Blue Maw", "Debby", "Redshadow"],
        "redshadow": ["Mayra", "Rolaf", "Jaw Jaw"],
        "lilli": ["Detective Guizmo", "Desperados", "Ripper"],
        "jager": ["Strix", "Shade", "Striker"],
        "noot": ["Cipher", "Inferno", "Pumpkin Pete"],
        "strix": ["Marco Pollo", "MacDyver", "Splashy"],
        "mayra": ["Rick Rock", "Eagle Eye", "Cleo"],
        "detective guizmo": ["Cleo", "Gigagoo", "Miss Bunny"],
        "jaw jaw": ["MacDyver", "Boomi", "Puca Hunter"],
        "macdyver": ["Rolaf", "Jet", "Crimson Guardian"],
        "pumpkin pete": ["Dunkan", "Wave", "Nad"],
        "mei long": ["Splashy", "Noot", "Aldric"],
        "imperius": ["Mei Long", "Rippin Finn", "Miss J"],
        "splashy": ["Rick Rock", "Poca Hunter", "Fragman"],
        "aldric": ["Piper Reese", "Quetza", "Laika"],
        "miss j": ["Rippin Finn", "Striker", "Desperados"],
        "dan": ["Nad", "Miss Bunny", "Blue Maw"],
        "bot mama": ["Ken Drift", "Wyatt", "Ellen"],
        "freez-b": ["DJ Equalizer", "Volcano", "Vlad"],
        "jack el padre": ["Sno", "Jaw Jaw", "Sogeki Chan"],
        "eagle eye": ["Ripper", "Nad", "Cleo"],
        "cyber girl": ["Boomi", "Darius", "Hakuryu"],
        "volcano": ["Cipher", "Blaise", "Ao"],
        "quetza": ["Meduza", "Crimson Guardian", "Queen Unicorn"],
        "vlad": ["Wyatt", "Poca Hunter", "Cleo"],
        "cyber cop": ["Vandal", "Noot", "Long Shot"],
        "captain polar": ["Cleo", "Wyatt", "Hakuryu"],
        "valkia": ["Wave", "Dunkan", "Sogeki-Chan"],
        "sogeki-chan": ["Zap Girl", "Cleo", "Duality"],
        "bibi": ["Striker", "Sno", "Queen Boom"],
        "mr.tiger": ["Nad", "Krystal", "Didi"],
        "sno": ["Rolaf", "Avalanche", "Bob"],
        "hakuryu": ["Ron1n", "Ripper", "Nautica"],
        "mr. doe": ["Big Paku", "Wave", "Soldatron"],
        "avalanche": ["Oksa", "Shade", "Lucha Muerta"],
        "nautica": ["Ripper", "Cactarina", "Nad"],
        "general mekk": ["Hubble", "Ron1n", "Dolb"],
        "ron1n": ["Ripper", "Nad", "Gigagoo"],
        "dr. crow": ["Mimi", "Hades5.1", "Takeshi"],
        "mimi": ["Evil Piper", "Nad", "Cleo"],
        "takeshi": ["Big Paku", "Shino-B", "APE-Suit"],
        "stella": ["Andrometa", "Nad", "Detective Guizmo"],
        "wave": ["Meduza", "Blaise", "Bob"],
        "k. boom": ["Bob", "Queen Boom", "C.O.B.R.A."],
        "bob": ["Ellen", "Blaise", "Bobbler"],
        "blaise": ["Mimi", "Rick Rock", "Long Shot"],
        "bonk": ["Dan", "Ape Suit", "BlueMaw"],
        "ellen": ["BlueMaw", "Mr. Tiger", "Ripper"],
        "bluemaw": ["Rolaf", "Cipher", "Debby"],
        "gabie & peanut": ["Vlad", "Ark-On", "RedShadow"],
        "ripper": ["Rolaf", "DJ Equalizer", "Queen Unicorn"],
        "cobra": ["Noot", "Darius", "Jay B"],
        "debby": ["Detective Guizmo", "Ollie", "Eagle Eye"],
        "crimson guardian": ["Gabie & Peanut", "Debby", "Blot"],
        "ken drift": ["Sunny", "Sergeant Crusher", "Darius"],
        "boomi": ["Big Paku", "Jay B", "Hannibal"],
        "shade": ["Sogeki Chan", "Ripper", "Zap Girl"],
        "sergeant crusher": ["Ao", "Sunny", "Dunkan"],
        "oksa": ["Redshadow", "Striker", "Jet"],
        "jaguar": ["Gigagoo", "Ripper", "Dolb"]
        # TODO: Add all other heroes and their specific counters here!
    }